/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMySportProfile"];
        put: operations["putMySportProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/consents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyConsents"];
        put?: never;
        post: operations["recordMyConsent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/consents/{record_id}/withdrawal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["withdrawMyConsent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questionnaires": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPublishedQuestionnaires"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questionnaires/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getQuestionnaireVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questionnaires/{version_id}/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitQuestionnaireVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMyAssessments"];
        put?: never;
        post: operations["createMyAssessment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPublishedExercises"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises/{exercise_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublishedExercise"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyCurrentProgram"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/current/weeks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMyCurrentProgramWeeks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/planned-sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyPlannedSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/planned-sessions/{session_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startMySessionRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session-runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["appendMySessionEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session-runs/{run_id}/discomfort-reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reportMyDiscomfort"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session-runs/{run_id}/completion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completeMySessionRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/daily-checkins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createMyDailyCheckin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/follow-ups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createMyFollowUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/questionnaires/{questionnaire_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Crée un brouillon. Cette opération ne le rend pas utilisable par les sportifs. */
        post: operations["createQuestionnaireDraftVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/questionnaire-versions/{version_id}/publication": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Publication atomique après validation distincte de l'auteur. */
        post: operations["publishQuestionnaireVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/rule-sets/{rule_set_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Crée une configuration sans code arbitraire et sans la publier. */
        post: operations["createRuleSetDraftVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/rule-set-versions/{version_id}/simulations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Accepte exclusivement une fixture marquée synthétique et ne produit aucun effet métier. */
        post: operations["simulateRuleSetVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/rule-set-versions/{version_id}/publication": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Publie l'ensemble après tests synthétiques et validation clinique formelle. */
        post: operations["publishRuleSetVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Format: uuid
         * @example 00000000-0000-7000-8000-000000000001
         */
        Uuid: string;
        User: {
            id: components["schemas"]["Uuid"];
            /**
             * @example [
             *       "user"
             *     ]
             */
            roles: string[];
        };
        SportProfileInput: {
            /** @example 1990 */
            birth_year: number;
            /**
             * @example [
             *       "road"
             *     ]
             */
            practices: string[];
            /** @enum {string} */
            level: "beginner" | "regular" | "experienced";
            /** @enum {string} */
            goal: "prevention" | "strength" | "return_after_break";
            /**
             * @example {
             *       "synthetic_day": 30
             *     }
             */
            weekly_availability: {
                [key: string]: unknown;
            };
            /**
             * @example [
             *       "synthetic_mat"
             *     ]
             */
            equipment: string[];
        };
        SportProfile: components["schemas"]["SportProfileInput"] & {
            version: number;
            /** Format: date-time */
            updated_at: string;
        };
        ConsentInput: {
            definition_version_id: components["schemas"]["Uuid"];
            /** @enum {string} */
            decision: "granted" | "refused";
        };
        ConsentRecord: components["schemas"]["ConsentInput"] & {
            id: components["schemas"]["Uuid"];
            /** Format: date-time */
            recorded_at: string;
        };
        ConsentState: {
            /** @example sensitive_data_processing */
            code: string;
            definition_version_id: components["schemas"]["Uuid"];
            required: boolean;
            /** @enum {string} */
            state: "not_recorded" | "granted" | "refused" | "withdrawn";
        };
        ConsentWithdrawal: {
            record_id: components["schemas"]["Uuid"];
            /** @enum {string} */
            status: "effective" | "workflow_started";
            /** Format: date-time */
            effective_at: string;
        };
        QuestionnaireSummary: {
            version_id: components["schemas"]["Uuid"];
            /** @example synthetic-safety-demo */
            code: string;
            /** @example 1 */
            version: number;
            /** @example Questionnaire fictif de contrat */
            title: string;
            content_hash: string;
        };
        QuestionnaireVersion: components["schemas"]["QuestionnaireSummary"] & {
            /** @example Exemple fictif sans portée clinique. */
            disclaimer: string;
            questions: {
                /** @example synthetic-q-001 */
                id: string;
                /** @enum {string} */
                type: "boolean" | "single_choice" | "multiple_choice" | "integer" | "decimal" | "text";
                /** @example Question fictive réservée au test du contrat. */
                label: string;
                required?: boolean;
                /**
                 * @example [
                 *       "synthetic-a",
                 *       "synthetic-b"
                 *     ]
                 */
                options?: string[];
            }[];
        };
        QuestionnaireSubmissionInput: {
            answers: {
                /** @example synthetic-q-001 */
                question_id: string;
                /** @example synthetic-a */
                value: unknown;
            }[];
        };
        QuestionnaireSubmission: {
            id: components["schemas"]["Uuid"];
            questionnaire_version_id: components["schemas"]["Uuid"];
            /** Format: date-time */
            submitted_at: string;
            evaluation: components["schemas"]["RuleResult"];
        };
        RuleResult: {
            /** @enum {string} */
            status: "matched" | "no_match" | "not_evaluated" | "blocked" | "simulation";
            /** @example none */
            action: string;
            /** @example CLINICAL_REFERENCE_NOT_PUBLISHED */
            reason_code: string;
            /** @example Aucune décision automatique n'a été appliquée. */
            explanation?: string;
            rule_set_version_id: components["schemas"]["Uuid"] | null;
            matched_rule_version_ids?: components["schemas"]["Uuid"][];
        };
        AssessmentInput: {
            definition_version_id: components["schemas"]["Uuid"];
            /**
             * @example [
             *       {
             *         "synthetic_measure": "synthetic-value"
             *       }
             *     ]
             */
            results: {
                [key: string]: unknown;
            }[];
        };
        Assessment: components["schemas"]["AssessmentInput"] & {
            id: components["schemas"]["Uuid"];
            /** Format: date-time */
            created_at: string;
        };
        AssessmentPage: {
            items: components["schemas"]["Assessment"][];
            next_cursor: string | null;
        };
        Exercise: {
            id: components["schemas"]["Uuid"];
            version_id: components["schemas"]["Uuid"];
            /** @example Exercice synthétique */
            title: string;
            /**
             * @example [
             *       "Instruction fictive."
             *     ]
             */
            instructions: string[];
            /**
             * @example [
             *       "Critère fictif non clinique."
             *     ]
             */
            stop_criteria: string[];
        };
        ExercisePage: {
            items: components["schemas"]["Exercise"][];
            next_cursor: string | null;
        };
        Program: {
            id: components["schemas"]["Uuid"];
            version_id: components["schemas"]["Uuid"];
            /** @enum {string} */
            status: "current" | "suspended" | "completed";
            /** @example Programme fictif pour test de contrat. */
            reason: string;
        };
        ProgramWeekPage: {
            items: {
                [key: string]: unknown;
            }[];
            next_cursor: string | null;
        };
        PlannedSession: {
            id: components["schemas"]["Uuid"];
            /**
             * Format: date
             * @example 2030-01-02
             */
            local_date: string;
            /** @example Europe/Paris */
            timezone: string;
            /** @enum {string} */
            kind: "strength" | "running" | "recovery" | "rest";
            version: number;
            items: {
                [key: string]: unknown;
            }[];
        };
        SessionRun: {
            id: components["schemas"]["Uuid"];
            planned_session_id: components["schemas"]["Uuid"];
            /** @enum {string} */
            status: "in_progress" | "completed" | "abandoned";
            version: number;
            /** Format: date-time */
            started_at: string;
        };
        SessionEventInput: {
            client_event_id: components["schemas"]["Uuid"];
            /** @enum {string} */
            type: "step_started" | "set_completed" | "paused" | "resumed" | "exercise_skipped";
            /** Format: date-time */
            occurred_at: string;
            payload: {
                [key: string]: unknown;
            };
        };
        DiscomfortInput: {
            client_event_id: components["schemas"]["Uuid"];
            /** @description Échelle de saisie */
            declared_level: number;
            /** @example Commentaire synthétique. */
            comment?: string;
            /** @enum {string} */
            action: "pause" | "stop";
        };
        DiscomfortReport: components["schemas"]["DiscomfortInput"] & {
            id: components["schemas"]["Uuid"];
            /** Format: date-time */
            recorded_at: string;
            evaluation: components["schemas"]["RuleResult"];
        };
        SessionCompletionInput: {
            perceived_effort: number;
            confidence: number;
            /** @example Bilan synthétique. */
            comment?: string;
        };
        DailyCheckinInput: {
            /**
             * Format: date
             * @example 2030-01-02
             */
            local_date: string;
            /** @example Europe/Paris */
            timezone: string;
            fatigue: number;
            sleep_quality: number;
            stress: number;
            motivation: number;
            discomfort?: number;
            /** @example Note synthétique. */
            comment?: string;
        };
        DailyCheckin: components["schemas"]["DailyCheckinInput"] & {
            id: components["schemas"]["Uuid"];
            /** Format: date-time */
            created_at: string;
            evaluation: components["schemas"]["RuleResult"];
        };
        FollowUpInput: {
            session_run_id: components["schemas"]["Uuid"];
            /** Format: date-time */
            observed_at: string;
            /** @example Europe/Paris */
            timezone: string;
            /**
             * @example {
             *       "synthetic_response": "synthetic-value"
             *     }
             */
            responses: {
                [key: string]: unknown;
            };
        };
        FollowUp: components["schemas"]["FollowUpInput"] & {
            id: components["schemas"]["Uuid"];
            evaluation: components["schemas"]["RuleResult"];
        };
        Progress: {
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
            series: {
                [key: string]: unknown;
            }[];
            /** @example Tendances descriptives sans interprétation médicale. */
            disclaimer: string;
        };
        QuestionnaireDraftInput: {
            /** @example fr-FR */
            locale: string;
            /** @example Questionnaire synthétique */
            title: string;
            /** @example Brouillon fictif sans portée clinique. */
            disclaimer: string;
            questions: {
                [key: string]: unknown;
            }[];
        };
        RuleSetDraftInput: {
            /** @example synthetic-v1 */
            input_schema_version: string;
            /** @description Expressions déclaratives utilisant uniquement des champs et opérateurs autorisés. */
            rules: {
                /** @example synthetic-rule-001 */
                code: string;
                /** @example 100 */
                priority: number;
                /**
                 * @example {
                 *       "operator": "synthetic_operator"
                 *     }
                 */
                expression: {
                    [key: string]: unknown;
                };
                /** @example synthetic_action */
                action: string;
                /** @example SYNTHETIC_REASON */
                reason_code: string;
                /** @example Explication synthétique. */
                explanation_template: string;
            }[];
        };
        RuleSimulationInput: {
            /** @constant */
            data_classification: "synthetic";
            /**
             * @example {
             *       "synthetic_field": "synthetic_value"
             *     }
             */
            fixture: {
                [key: string]: unknown;
            };
        };
        PublicationInput: {
            validation_id: components["schemas"]["Uuid"];
            expected_content_hash: string;
        };
        ClinicalResourceVersion: {
            id: components["schemas"]["Uuid"];
            version: number;
            /** @enum {string} */
            status: "draft" | "in_review" | "validated" | "published" | "retired" | "disabled";
            content_hash: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            published_at?: string | null;
        };
        InvalidField: {
            field: string;
            code: string;
        };
        ErrorEnvelope: {
            error: {
                /** @example VALIDATION_FAILED */
                code: string;
                /** @example Certaines informations sont invalides. */
                user_message?: string;
                /** @example Request validation failed. */
                technical_message: string;
                invalid_fields: components["schemas"]["InvalidField"][];
                /** @example req_00000000-0000-7000-8000-000000000099 */
                request_id: string;
            };
        };
    };
    responses: {
        /** @description Erreur uniforme sans information sensible */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Version, état ou clé d'idempotence en conflit */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        IdempotencyKey: string;
        IfMatch: string;
        Cursor: string;
        Limit: number;
        RecordId: components["schemas"]["Uuid"];
        VersionId: components["schemas"]["Uuid"];
        SessionId: components["schemas"]["Uuid"];
        RunId: components["schemas"]["Uuid"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Utilisateur applicatif courant */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getMySportProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profil sportif du propriétaire authentifié */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SportProfile"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    putMySportProfile: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SportProfileInput"];
            };
        };
        responses: {
            /** @description Profil créé ou remplacé */
            200: {
                headers: {
                    /** @description Version optimiste */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SportProfile"];
                };
            };
            409: components["responses"]["Conflict"];
            default: components["responses"]["Error"];
        };
    };
    getMyConsents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Définitions applicables et décisions courantes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ConsentState"][];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    recordMyConsent: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsentInput"];
            };
        };
        responses: {
            /** @description Décision append-only enregistrée */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentRecord"];
                };
            };
            409: components["responses"]["Conflict"];
            default: components["responses"]["Error"];
        };
    };
    withdrawMyConsent: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                record_id: components["parameters"]["RecordId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Retrait pris en compte ou workflow associé lancé */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentWithdrawal"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listPublishedQuestionnaires: {
        parameters: {
            query?: {
                purpose?: "initial_safety";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Versions publiées compatibles avec le client */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["QuestionnaireSummary"][];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getQuestionnaireVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Version publiée immuable */
            200: {
                headers: {
                    /** @description Empreinte du contenu */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionnaireVersion"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    submitQuestionnaireVersion: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                version_id: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionnaireSubmissionInput"];
            };
        };
        responses: {
            /** @description Soumission et état d'évaluation */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionnaireSubmission"];
                };
            };
            409: components["responses"]["Conflict"];
            default: components["responses"]["Error"];
        };
    };
    listMyAssessments: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bilans du propriétaire */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createMyAssessment: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssessmentInput"];
            };
        };
        responses: {
            /** @description Bilan initial enregistré sans interprétation libre */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assessment"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listPublishedExercises: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dernières versions publiées uniquement */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExercisePage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getPublishedExercise: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Version publiée exacte */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exercise"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getMyCurrentProgram: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Programme courant et justification de version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Program"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listMyCurrentProgramWeeks: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Semaines et séances planifiées */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramWeekPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getMyPlannedSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Séance appartenant à l'utilisateur */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannedSession"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    startMySessionRun: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exécution créée ou réponse initiale rejouée */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionRun"];
                };
            };
            409: components["responses"]["Conflict"];
            default: components["responses"]["Error"];
        };
    };
    appendMySessionEvent: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionEventInput"];
            };
        };
        responses: {
            /** @description Événement accepté une seule fois */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    reportMyDiscomfort: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscomfortInput"];
            };
        };
        responses: {
            /** @description Gêne enregistrée sans diagnostic */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscomfortReport"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    completeMySessionRun: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCompletionInput"];
            };
        };
        responses: {
            /** @description Séance terminée */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionRun"];
                };
            };
            409: components["responses"]["Conflict"];
            default: components["responses"]["Error"];
        };
    };
    createMyDailyCheckin: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DailyCheckinInput"];
            };
        };
        responses: {
            /** @description Point quotidien et état d'évaluation */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyCheckin"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createMyFollowUp: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FollowUpInput"];
            };
        };
        responses: {
            /** @description Suivi différé et décision explicable ou état non évalué */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowUp"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getMyProgress: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tendances descriptives, sans causalité médicale */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Progress"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createQuestionnaireDraftVersion: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                questionnaire_id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionnaireDraftInput"];
            };
        };
        responses: {
            /** @description Brouillon versionné créé et audité */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClinicalResourceVersion"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    publishQuestionnaireVersion: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                version_id: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublicationInput"];
            };
        };
        responses: {
            /** @description Version publiée immuable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClinicalResourceVersion"];
                };
            };
            409: components["responses"]["Conflict"];
            default: components["responses"]["Error"];
        };
    };
    createRuleSetDraftVersion: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                rule_set_id: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleSetDraftInput"];
            };
        };
        responses: {
            /** @description Brouillon créé et audité */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClinicalResourceVersion"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    simulateRuleSetVersion: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                version_id: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleSimulationInput"];
            };
        };
        responses: {
            /** @description Résultat de simulation audité */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleResult"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    publishRuleSetVersion: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                version_id: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublicationInput"];
            };
        };
        responses: {
            /** @description Jeu publié de manière atomique */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClinicalResourceVersion"];
                };
            };
            409: components["responses"]["Conflict"];
            default: components["responses"]["Error"];
        };
    };
}
